Repository agarrharr/awesome-cli-apps, pull requests merged in 2019-07, with the labels that each got.

#338 Add Cataclysm-DDA
  readme.md
Labels: needs review

#346 Rename 'Terminal Utils' to 'Terminal Sharing Utils'
  readme.md
Labels: category

#345 Add 'Shell Utilities' subcategory
  readme.md
Labels: category

#343 Add 'Boilerplate' subcategory
  readme.md
Labels: category

#347 Add lf
  readme.md
Labels: pending

#344 Add 'System Interaction Utilities' subcategory
  readme.md
Labels: category

#351 Add dark-mode
  readme.md
Labels: pending

#355 Fix TODO case
  readme.md
Labels: needs review
