Repository agarrharr/awesome-cli-apps, pull requests merged in 2019-03, with the labels that each got.

#266 Add grip
  readme.md
Labels: pending

#275 Add JSON subcategory
  readme.md
Labels: enhancement, needs review

#273 Added Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, needs review

#289 Add new Emoji subcategory under Other
  readme.md
Labels: needs review

#295 Add npm-check-updates
  readme.md
Labels: needs review

#297 Add new Theming/Customization subcategory to Utilities
  readme.md
Labels: category, needs review

#296 Add flog
  readme.md
Labels: pending

#294 Add 'npm' subcategory
  readme.md
Labels: category, pending

#300 Remove starring
  readme.md
Labels: needs review

#301 Add pywal
  readme.md
Labels: needs review

#243 Add pm2
  readme.md
Labels: pending

#311 Add kakoune
  readme.md
Labels: pending

#305 Cleanup descriptions
  readme.md
Labels: enhancement
